version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - symfony
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: symfony_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - symfony
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: importTest
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: symfony
      MYSQL_USER: symfony
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - symfony

volumes:
  dbdata:
    driver: local

networks:
  symfony:
    driver: bridge